version: '3.4'
services:
  web:
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    restart: always
  mongodb_container:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: