version: '3.4'
services:
  web:
    build:
      context: .
      network: host
    volumes:
      - .:/code
    ports:
      - 5000:5000

    depends_on:
      - redis
  redis:
    image: "redis:alpine"